### PR TITLE
cut files 

### PR DESCRIPTION
**Pull request by PRamoneda**
Reducing audio size files for size optimization purpose.

### CODE REVIEW

**Comment by magdalenafuentes** [comment]
@PRamoneda let me know when this one is ready for review!

**Comment by PRamoneda** [comment]
> @PRamoneda let me know when this one is ready for review!

@magdalenafuentes, it is ready.

**Comment by rabitt** [comment]
@PRamoneda This is perfect! Would you be ok doing it for some more of the loaders? Looking at the size of the files, it looks like the other ones with long files are:
* cante100
* irmas
* saraga_carnatic
* saraga_hindustani

**Comment by genisplaja** [comment]
> @PRamoneda This is perfect! Would you be ok doing it for some more of the loaders? Looking at the size of the files, it looks like the other ones with long files are:
> 
>     * cante100
> 
>     * irmas
> 
>     * saraga_carnatic
> 
>     * saraga_hindustani

Yes, I will do it for these four! I already made `saraga_carnatic` and `saraga_hindustani` audios way shorter, but it seems that it would be interesting to cut them even more! I will also reduce `cante100`'s spectrum and audio. `irmas` has a wav file that lasts for 20 seconds. I will make it shorter as well!!

**Comment by rabitt** [comment]
@genisplaja thanks! Maybe it's easiest to do it as a separate PR. I'll merge this PR, and update #360

**Review by rabitt — APPROVED** [review]

**Pull request merged**
