### PR TITLE
remove line audio size in gs tempo test track

### PR DESCRIPTION
**Pull request by PRamoneda**
This is a recurrent error.

In CircleCi librosa works nice. However, In other systems, sometimes the size is a bit different.

If someone has a cleaner proposal, we are open minded :D

### CODE REVIEW

**Comment by magdalenafuentes** [comment]
So you're testing locally and the size of the file is not right? Just sanity check: are you sure is the same exact audio file?

**Comment by PRamoneda** [comment]
Yes! @genisplaja dicussed this topic with rachel in one meeting

**Comment by magdalenafuentes** [comment]
It happens in other loaders as well?

**Review by magdalenafuentes — APPROVED** [review]
If you discussed this with @rabitt already let's merge since is a current fail

**Comment by rabitt** [comment]
I get an error for this test locally as well, coming from slight differences in different mp3 decoders. I'm ok with removing it!

**Review by rabitt — APPROVED** [review]

**Pull request merged**
