### PR TITLE
remove # -\*- coding: utf-8 -\*-\n  header

### PR DESCRIPTION
**Pull request by PRamoneda**
It is a legacy from Python2 support. However, currently, python2 is not supported by mirdata

### CODE REVIEW

**Review by magdalenafuentes — COMMENTED** [review]
@PRamoneda do you know if this has any effect in the editor's (IDE) encoding?

**Comment by PRamoneda** [comment]
in sublime and PyCharm letters as ñ works

**Review by magdalenafuentes — APPROVED** [review]

**Comment by PRamoneda** [comment]
And python3 libraries are without the head. Moreover, see for example this post : https://adamj.eu/tech/2019/03/13/dropping-python-2-support/

**Comment by rabitt** [comment]
@PRamoneda feel free to merge this at your convenience!

**Pull request merged**
