### PR TITLE
Fix destination directory for cante100

### PR DESCRIPTION
**Pull request by genisplaja**
I have checked the other datasets and that's just a cante100 problem. This PR fixes it. Thanks @magdalenafuentes for the catch!!

### CODE REVIEW

**Review by magdalenafuentes — APPROVED** [review]
Thanks for this Genis, looks good to me!

Could you add a comment in CONTRIBUTING.md about making sure that partial downloads go to the directory they're meant to go or something like that? Then this is ready to merge

**Comment by magdalenafuentes** [comment]
This closes #357

**Comment by genisplaja** [comment]
Sure! I added a comment over the `REMOTES` dictionary example. Please let me know what you think about it. Thanks!!

**Review by magdalenafuentes — APPROVED** [review]
Ready to merge!

**Pull request merged**
